import type { DifficultyLevel, LearningPathId } from "./taxonomy";

export type ContentType = "article" | "tutorial" | "tool";

export interface ContentMeta {
  id: string;
  slug: string;
  type: ContentType;
  title: string;
  description: string;

  // ── Taxonomy fields ───────────────────────────────────────────────────────
  /** Taxonomy category id (maps to CATEGORIES in taxonomy.ts) */
  categoryId: string;
  /** Display label for the category */
  category: string;
  /** Tailwind bg class for the category badge */
  categoryColor: string;
  /** Difficulty level */
  level?: DifficultyLevel;
  /** Estimated reading / usage time (display string) */
  readTime: string;
  /** Estimated time in minutes (for sorting/filtering) */
  estimatedMinutes?: number;
  /** Learning paths this content belongs to */
  learningPaths?: LearningPathId[];
  /** Slugs of content that should be completed before this */
  prerequisites?: string[];
  /** What the reader will learn */
  objectives?: string[];
  /** Searchable tags */
  tags?: string[];
  /** Subcategory for grouping within a type (e.g. "languages" | "frameworks" for tutorials) */
  subcategory?: string;

  // ── Publication ───────────────────────────────────────────────────────────
  publishedAt: string; // ISO "YYYY-MM-DD"
  featured?: boolean;
}

export const allContent: ContentMeta[] = [
  // ── Tutorials ────────────────────────────────────────────────────────────────
  {
    id: "c-lang",
    slug: "c-lang",
    type: "tutorial",
    title: "C: de cero a avanzado",
    description:
      "Tutorial completo de C: variables, operadores, control de flujo, funciones, arrays, strings, punteros y structs. Con 25 ejercicios.",
    categoryId: "c",
    category: "C",
    categoryColor: "bg-blue-700",
    level: "beginner",
    readTime: "75 min",
    estimatedMinutes: 75,
    learningPaths: ["fullstack"],
    prerequisites: [],
    objectives: [
      "Entender variables, tipos y operadores en C",
      "Dominar estructuras de control y funciones",
      "Comprender punteros y gestión manual de memoria",
      "Trabajar con arrays, strings y structs",
    ],
    subcategory: "languages",
    publishedAt: "2026-06-23",
    featured: true,
    tags: ["C", "Punteros", "Sistemas", "Memoria", "Programación"],
  },
  {
    id: "cpp-lang",
    slug: "cpp-lang",
    type: "tutorial",
    title: "C++ moderno: cero a avanzado",
    description:
      "Tutorial completo de C++ moderno: POO, herencia, polimorfismo, constructores, STL, smart pointers, move semantics y E/S de archivos.",
    categoryId: "cpp",
    category: "C++",
    categoryColor: "bg-cyan-600",
    level: "intermediate",
    readTime: "80 min",
    estimatedMinutes: 80,
    learningPaths: ["fullstack"],
    prerequisites: ["c-lang"],
    objectives: [
      "Aplicar POO: clases, herencia y polimorfismo",
      "Usar la STL: vectores, maps, algoritmos",
      "Gestionar memoria con smart pointers",
      "Dominar move semantics y rvalue references",
    ],
    subcategory: "languages",
    publishedAt: "2026-06-23",
    featured: true,
    tags: ["C++", "POO", "STL", "Smart Pointers", "Moderno"],
  },
  {
    id: "typescript",
    slug: "typescript",
    type: "tutorial",
    title: "Introducción a TypeScript",
    description:
      "Aprende TypeScript desde tipos básicos hasta genéricos y Utility Types. Con 5 ejercicios prácticos.",
    categoryId: "typescript",
    category: "TypeScript",
    categoryColor: "bg-blue-500",
    level: "beginner",
    readTime: "35 min",
    estimatedMinutes: 35,
    learningPaths: ["fullstack", "frontend", "backend"],
    prerequisites: [],
    objectives: [
      "Entender el sistema de tipos de TypeScript",
      "Configurar un proyecto con tsconfig.json",
      "Usar interfaces, types y generics básicos",
      "Integrar TypeScript en un proyecto existente",
    ],
    subcategory: "languages",
    publishedAt: "2026-06-21",
    featured: true,
    tags: ["TypeScript", "JavaScript", "Programación", "tipado"],
  },
  // ── Articles ─────────────────────────────────────────────────────────────────
  {
    id: "svg",
    slug: "svg",
    type: "article",
    title: "Mejores webs de SVG",
    description:
      "Una selección de plataformas con SVGs gratuitos y de alta calidad para tus proyectos.",
    categoryId: "resources",
    category: "Recursos",
    categoryColor: "bg-amber-400",
    level: "beginner",
    readTime: "5 min",
    estimatedMinutes: 5,
    learningPaths: ["frontend"],
    prerequisites: [],
    objectives: [
      "Conocer las mejores fuentes de SVGs gratuitos",
      "Saber cuándo usar cada plataforma",
    ],
    publishedAt: "2026-06-21",
    tags: ["SVG", "Recursos", "Diseño", "frontend"],
  },
  {
    id: "database",
    slug: "database",
    type: "article",
    title: "Hosting de bases de datos",
    description:
      "Las mejores opciones en la nube para alojar tu base de datos, con planes gratuitos incluidos.",
    categoryId: "supabase",
    category: "Backend",
    categoryColor: "bg-emerald-400",
    level: "beginner",
    readTime: "5 min",
    estimatedMinutes: 5,
    learningPaths: ["fullstack", "backend"],
    prerequisites: [],
    objectives: [
      "Comparar las principales plataformas de hosting de bases de datos",
      "Elegir la opción más adecuada según el proyecto",
    ],
    publishedAt: "2026-06-21",
    featured: true,
    tags: ["Base de datos", "Cloud", "Backend", "bases de datos"],
  },
  {
    id: "frontend-hosting",
    slug: "frontend-hosting",
    type: "article",
    title: "Mejor hosting frontend",
    description:
      "Vercel, Netlify, Cloudflare Pages y más. Análisis honesto con pros, contras y cuándo usar cada una.",
    categoryId: "resources",
    category: "Recursos",
    categoryColor: "bg-violet-400",
    level: "beginner",
    readTime: "8 min",
    estimatedMinutes: 8,
    learningPaths: ["frontend", "fullstack"],
    prerequisites: [],
    objectives: [
      "Conocer las mejores plataformas de hosting frontend",
      "Elegir la opción adecuada según el proyecto y framework",
    ],
    publishedAt: "2026-06-25",
    featured: true,
    tags: ["Frontend", "Hosting", "Vercel", "Netlify", "Cloudflare", "deploy"],
  },
  {
    id: "backend-hosting",
    slug: "backend-hosting",
    type: "article",
    title: "Mejor hosting backend",
    description:
      "Railway, Render, Fly.io, Koyeb y más. Guía completa para elegir dónde alojar tu API o servidor en 2026.",
    categoryId: "supabase",
    category: "Backend",
    categoryColor: "bg-emerald-500",
    level: "beginner",
    readTime: "8 min",
    estimatedMinutes: 8,
    learningPaths: ["backend", "fullstack"],
    prerequisites: [],
    objectives: [
      "Comparar las principales plataformas de hosting backend",
      "Elegir la mejor opción según el caso de uso y presupuesto",
    ],
    publishedAt: "2026-06-25",
    featured: true,
    tags: [
      "Backend",
      "Hosting",
      "Railway",
      "Render",
      "Fly.io",
      "deploy",
      "servidor",
    ],
  },
  // ── Tools ─────────────────────────────────────────────────────────────────────
  {
    id: "palette-generator",
    slug: "palette-generator",
    type: "tool",
    title: "Generador de paletas",
    description:
      "Elige un color primario y secundario y genera automáticamente una paleta de 9 colores. Edita cada tono individualmente y obtén una puntuación de armonía, contraste y accesibilidad.",
    categoryId: "design",
    category: "Diseño",
    categoryColor: "bg-pink-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: ["frontend"],
    prerequisites: [],
    objectives: [
      "Generar paletas de color coherentes a partir de dos colores base",
      "Evaluar accesibilidad WCAG de la paleta",
      "Exportar los colores como variables CSS",
    ],
    publishedAt: "2026-06-25",
    featured: true,
    tags: ["Color", "Paleta", "Diseño", "CSS", "Accesibilidad", "WCAG", "UI"],
  },
  {
    id: "qr-generator",
    slug: "qr-generator",
    type: "tool",
    title: "Generador de QR",
    description:
      "Genera códigos QR a partir de texto o URLs. Descarga como PNG o copia al instante.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-amber-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["QR", "Código", "Compartir", "URL", "Herramienta"],
  },
  {
    id: "uuid-generator",
    slug: "uuid-generator",
    type: "tool",
    title: "Generador de UUIDs",
    description:
      "Genera UUIDs v4 y v7 al instante. Copia individual o en lote, con o sin guiones.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-sky-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["UUID", "Identificador", "API", "Base de datos", "Herramienta"],
  },
  {
    id: "timestamp-converter",
    slug: "timestamp-converter",
    type: "tool",
    title: "Conversor de timestamps",
    description:
      "Convierte timestamps Unix a fecha legible y viceversa. Soporta segundos, milisegundos y formatos ISO.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-teal-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["Timestamp", "Unix", "Fecha", "Conversión", "Herramienta"],
  },
  {
    id: "case-converter",
    slug: "case-converter",
    type: "tool",
    title: "Conversor de mayúsculas",
    description:
      "Convierte texto entre camelCase, snake_case, kebab-case, PascalCase, UPPER_CASE y más.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-rose-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-07-01",
    featured: false,
    tags: [
      "Texto",
      "Case",
      "camelCase",
      "snake_case",
      "kebab-case",
      "Herramienta",
    ],
  },
  {
    id: "diff-checker",
    slug: "diff-checker",
    type: "tool",
    title: "Comparador de texto",
    description:
      "Compara dos textos lado a lado y resalta las diferencias línea por línea.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-indigo-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-07-01",
    featured: false,
    tags: ["Diff", "Comparar", "Texto", "Código", "Herramienta"],
  },
  {
    id: "pdf-editor",
    slug: "pdf-editor",
    type: "tool",
    title: "Editor de PDF",
    description:
      "Sube, edita y descarga PDFs desde el navegador. Rota, reordena y elimina páginas, o combina varios PDFs en uno.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-red-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["PDF", "Edición", "Combinar", "Rotar", "Herramienta"],
  },
  {
    id: "pdf-to-excel",
    slug: "pdf-to-excel",
    type: "tool",
    title: "Facturas PDF a Excel",
    description:
      "Convierte facturas PDF en celdas de Excel. Sube tu factura, revisa los datos extraídos y copia directamente al portapapeles.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-red-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-01",
    featured: false,
    tags: ["PDF", "Excel", "Facturas", "Invoice", "Herramienta"],
  },
  {
    id: "sql-builder",
    slug: "sql-builder",
    type: "tool",
    title: "Constructor SQL interactivo",
    description:
      "Construye consultas SELECT cliqueando tablas y columnas. Parseo automático de DDL y generación de JOINs por clave foránea.",
    categoryId: "sql",
    category: "SQL",
    categoryColor: "bg-blue-600",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: ["fullstack", "backend", "frontend"],
    prerequisites: [],
    objectives: [
      "Construir consultas SELECT visualmente",
      "Explorar esquemas de base de datos",
      "Entender JOINs a través de claves foráneas",
      "Practicar WHERE, GROUP BY y ORDER BY",
    ],
    publishedAt: "2026-07-30",
    featured: true,
    tags: [
      "SQL",
      "SELECT",
      "JOIN",
      "Constructor",
      "Herramienta",
      "Interactivo",
    ],
  },
  {
    id: "markdown-preview",
    slug: "markdown-preview",
    type: "tool",
    title: "Markdown Preview",
    description: "Editor markdown split-pane con preview en vivo. Escribe en el lado izquierdo y ve el resultado renderizado en el derecho.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-indigo-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["Markdown", "Editor", "Preview", "Herramienta"],
  },
  {
    id: "jwt-decoder",
    slug: "jwt-decoder",
    type: "tool",
    title: "JWT Decoder",
    description: "Decodifica tokens JWT instantáneamente. Visualiza header, payload y firma con expiration warnings.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-cyan-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["JWT", "Token", "Auth", "Herramienta"],
  },
  {
    id: "url-encoder-decoder",
    slug: "url-encoder-decoder",
    type: "tool",
    title: "URL Encoder/Decoder",
    description: "Codifica y decodifica URLs, query params y componentes. Auto-detección de input codificado.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-cyan-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["URL", "Encode", "Decode", "Herramienta"],
  },
  {
    id: "cron-builder",
    slug: "cron-builder",
    type: "tool",
    title: "Cron Builder",
    description: "Construye expresiones cron visualmente con presets comunes y preview de próximas ejecuciones.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-amber-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["Cron", "Scheduler", "Timer", "Herramienta"],
  },
  {
    id: "hash-generator",
    slug: "hash-generator",
    type: "tool",
    title: "Hash Generator",
    description: "Genera hashes MD5, SHA-1, SHA-256 y SHA-512 de texto en tiempo real usando Web Crypto API.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-amber-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["Hash", "SHA", "MD5", "Security", "Herramienta"],
  },
  {
    id: "json-to-ts",
    slug: "json-to-ts",
    type: "tool",
    title: "JSON → TypeScript",
    description: "Convierte JSON a interfaces o types de TypeScript en tiempo real. Soporta objetos anidados, arrays y nulls.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-cyan-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["JSON", "TypeScript", "Types", "Herramienta"],
  },
  {
    id: "html-entity",
    slug: "html-entity",
    type: "tool",
    title: "HTML Entity Encoder",
    description: "Codifica y decodifica entidades HTML. Convierte caracteres especiales a sus entidades y viceversa.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-indigo-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["HTML", "Entities", "Encode", "Herramienta"],
  },
  {
    id: "lorem-ipsum",
    slug: "lorem-ipsum",
    type: "tool",
    title: "Lorem Ipsum Generator",
    description: "Genera texto placeholder personalizable con opción de tags HTML. Perfecto para maquetación y diseño.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-amber-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["Lorem", "Placeholder", "Design", "Herramienta"],
  },
  {
    id: "regex-visualizer",
    slug: "regex-visualizer",
    type: "tool",
    title: "Regex Visualizer",
    description: "Visualiza la estructura de expresiones regulares como diagrama de tokens. Test con highlights en tiempo real.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-indigo-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["Regex", "RegExp", "Visual", "Herramienta"],
  },
  {
    id: "barcode-generator",
    slug: "barcode-generator",
    type: "tool",
    title: "Barcode Generator",
    description: "Genera códigos de barras (Code128, Code39, EAN-13) como SVG/PNG descargables.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-amber-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["Barcode", "Code128", "EAN", "Herramienta"],
  },
  {
    id: "css-gradient",
    slug: "css-gradient",
    type: "tool",
    title: "CSS Gradient Builder",
    description: "Constructor visual de gradientes CSS lineales y radiales con preview en vivo y código copiable.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-fuchsia-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["CSS", "Gradient", "Design", "Herramienta"],
  },
  {
    id: "image-to-base64",
    slug: "image-to-base64",
    type: "tool",
    title: "Image → Base64",
    description: "Convierte imágenes a Base64 y viceversa. Soporta JPG, PNG, GIF, SVG y WebP con preview.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-red-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["Image", "Base64", "Convert", "Herramienta"],
  },
  {
    id: "mock-data",
    slug: "mock-data",
    type: "tool",
    title: "Mock Data Generator",
    description: "Genera datos falsos realistas: personas, comercio, números, texto y fechas. Exporta como JSON.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-amber-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: [],
    prerequisites: [],
    publishedAt: "2026-08-15",
    featured: false,
    tags: ["Mock", "Fake", "Data", "Herramienta"],
  },
  {
    id: "git",
    slug: "git",
    type: "tutorial",
    title: "Git: de cero a conflictos",
    description:
      "Guía exhaustiva de Git: configuración, comandos esenciales, ramas, remotos, resolución de conflictos paso a paso, comandos avanzados y flujos de trabajo en equipo.",
    categoryId: "git",
    category: "Git",
    categoryColor: "bg-orange-600",
    level: "beginner",
    readTime: "60 min",
    estimatedMinutes: 60,
    subcategory: "tools",
    learningPaths: ["fullstack", "frontend", "backend"],
    prerequisites: [],
    objectives: [
      "Entender el modelo de datos de Git (commits, ramas, HEAD)",
      "Dominar los comandos del día a día",
      "Resolver conflictos de merge y rebase con confianza",
      "Usar comandos avanzados: bisect, reflog, cherry-pick",
      "Conocer los flujos de trabajo más usados en equipos",
    ],
    publishedAt: "2026-06-25",
    featured: true,
    tags: [
      "Git",
      "Control de versiones",
      "Conflictos",
      "Ramas",
      "GitHub",
      "DevOps",
    ],
  },
  // ── OpenCode Models (deepdive) ───────────────────────────────────────────────
  {
    id: "opencode-models",
    slug: "opencode-models",
    type: "tutorial",
    title:
      "Modelos de IA en OpenCode: guía completa (OpenAI, Claude, Copilot, Ollama y locales)",
    description:
      "Guía completa de todos los proveedores y modelos compatibles con OpenCode: OpenAI, Anthropic, GitHub Copilot, Ollama, modelos locales y comparativa para elegir el mejor según tu caso de uso.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-emerald-500",
    level: "intermediate",
    readTime: "15 min",
    estimatedMinutes: 15,
    subcategory: "tools",
    learningPaths: [],
    prerequisites: ["opencode"],
    objectives: [
      "Conocer los más de 75 proveedores compatibles con OpenCode",
      "Configurar OpenAI, Anthropic, GitHub Copilot y Ollama paso a paso",
      "Entender el soporte de visión y cuándo usarlo",
      "Ejecutar modelos locales con Ollama, LM Studio y llama.cpp",
      "Elegir el modelo adecuado según la tarea: código, diseño, equilibrio u offline",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "OpenCode",
      "OpenAI",
      "Claude",
      "Ollama",
      "Modelos locales",
      "LLM",
      "IA",
      "GPT",
      "Copilot",
    ],
  },
  // ── OpenCode tutorial ────────────────────────────────────────────────────────
  {
    id: "opencode",
    slug: "opencode",
    type: "tutorial",
    title: "Qué es OpenCode y cómo empezar a usarlo",
    description:
      "Aprende qué es OpenCode, para qué sirve, cómo instalarlo y usarlo como asistente de IA en tu terminal. Desde cero en menos de 5 minutos.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-emerald-500",
    level: "beginner",
    readTime: "10 min",
    estimatedMinutes: 10,
    subcategory: "tools",
    learningPaths: [],
    prerequisites: [],
    objectives: [
      "Entender qué es OpenCode y cómo funciona",
      "Conocer sus casos de uso principales",
      "Instalar y configurar OpenCode en tu sistema",
      "Ejecutar tu primer flujo de trabajo con OpenCode",
      "Dominar los comandos esenciales del día a día",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["OpenCode", "IA", "Terminal", "CLI", "Asistente", "Productividad"],
  },
  {
    id: "ai-project",
    slug: "ai-project",
    type: "tutorial",
    title: "Cómo empezar un proyecto con IA",
    description:
      "Guía práctica para construir proyectos asistidos por IA: crea un AGENTS.md, un DESIGN.md, estructura los archivos de contexto y establece un flujo de trabajo que maximice la productividad con asistentes como Claude, GPT y OpenCode.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-emerald-500",
    level: "beginner",
    readTime: "20 min",
    estimatedMinutes: 20,
    subcategory: "tools",
    learningPaths: [],
    prerequisites: ["opencode"],
    objectives: [
      "Crear un AGENTS.md o CLAUDE.md con reglas y stack del proyecto",
      "Diseñar un DESIGN.md que unifique colores, tipografía y estilos",
      "Estructurar archivos de contexto complementarios (MEMORY.md, ARCHITECTURE.md, API.md)",
      "Dar instrucciones efectivas a la IA para obtener resultados consistentes",
      "Establecer un flujo de trabajo diario con gestión de contexto",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "IA",
      "OpenCode",
      "CLAUDE.md",
      "AGENTS.md",
      "DESIGN.md",
      "Contexto",
      "Tutorial",
      "Productividad",
      "Workflow",
    ],
  },
  // ── Skills ─────────────────────────────────────────────────────────
  {
    id: "skills-tutorial",
    slug: "skills-tutorial",
    type: "tutorial",
    title: "Cómo usar Skills en OpenCode",
    description:
      "Guía completa del sistema de Skills de OpenCode: qué son, cómo cargarlos, cómo crearlos y cómo sacarles el máximo partido en tus proyectos. Incluye catálogo de skills disponibles.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "beginner",
    readTime: "12 min",
    estimatedMinutes: 12,
    subcategory: "tools",
    learningPaths: ["ai-engineer"],
    prerequisites: ["opencode"],
    objectives: [
      "Entender qué son los Skills y cómo funcionan",
      "Aprender a cargar skills desde el chat o desde AGENTS.md",
      "Conocer la estructura de un SKILL.md",
      "Crear skills personalizados para tus proyectos",
      "Saber dónde guardar skills (global vs local)",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Skills",
      "OpenCode",
      "AGENTS.md",
      "CLAUDE.md",
      "Instrucciones",
      "Personalización",
    ],
  },
  {
    id: "skills-catalog",
    slug: "skills-catalog",
    type: "article",
    title: "Skills disponibles para OpenCode",
    description:
      "Catálogo completo de todos los Skills de OpenCode: diseño, desarrollo, herramientas, base de datos, inteligencia de código y contenido. Cada skill con su descripción, caso de uso y cómo activarlo.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "beginner",
    readTime: "8 min",
    estimatedMinutes: 8,
    learningPaths: ["ai-engineer"],
    prerequisites: ["skills-tutorial"],
    objectives: [
      "Conocer los 16 skills disponibles en OpenCode",
      "Entender qué hace cada skill y cuándo usarlo",
      "Saber cómo activar cada skill",
      "Identificar qué skills aplicar según la tarea",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Skills",
      "OpenCode",
      "skills",
      "Catálogo",
      "Diseño",
      "Desarrollo",
      "Herramientas",
      "BD",
      "Presentaciones",
    ],
  },
  // ── MCP ─────────────────────────────────────────────────────────────
  {
    id: "instalar-mcp",
    slug: "instalar-mcp",
    type: "tutorial",
    title: "Cómo instalar MCP para agentes de IA",
    description:
      "Guía completa del Model Context Protocol (MCP): qué es, cómo funciona y cómo configurar servidores MCP en OpenCode, Claude Code y Cursor.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "intermediate",
    readTime: "15 min",
    estimatedMinutes: 15,
    subcategory: "tools",
    learningPaths: ["ai-engineer"],
    prerequisites: ["opencode"],
    objectives: [
      "Entender qué es MCP y cómo funciona (cliente-servidor, JSON-RPC)",
      "Configurar servidores MCP en OpenCode, Claude Code y Cursor",
      "Conocer los tipos de servidores (stdio vs HTTP+SSE)",
      "Aplicar buenas prácticas de seguridad con tokens y permisos",
      "Verificar que los MCPs funcionan correctamente",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "MCP",
      "OpenCode",
      "Claude",
      "Cursor",
      "IA",
      "Herramientas",
      "Protocolo",
      "Integración",
    ],
  },
  {
    id: "mcp-servers",
    slug: "mcp-servers",
    type: "article",
    title: "Servidores MCP para potenciar tu IA",
    description:
      "Catálogo completo de los servidores MCP más usados en 2026: Filesystem, GitHub, Playwright, PostgreSQL, Supabase, Stripe, Slack y 13 más. Cada uno con su paquete npm, configuración y caso de uso.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "intermediate",
    readTime: "10 min",
    estimatedMinutes: 10,
    learningPaths: ["ai-engineer"],
    prerequisites: ["instalar-mcp"],
    objectives: [
      "Conocer los servidores MCP más importantes del ecosistema",
      "Saber qué comando npm usar para instalar cada uno",
      "Entender qué casos de uso cubre cada servidor",
      "Identificar qué variables de entorno necesita cada MCP",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "MCP",
      "Servidores",
      "Filesystem",
      "GitHub",
      "Playwright",
      "PostgreSQL",
      "Supabase",
      "Stripe",
      "Slack",
      "Herramientas",
    ],
  },
  // ── Crear MCP ──────────────────────────────────────────────────────────
  {
    id: "crear-mcp",
    slug: "crear-mcp",
    type: "tutorial",
    title: "Cómo crear tu propio servidor MCP",
    description:
      "Guía práctica para construir servidores MCP desde cero con TypeScript y el SDK oficial. Aprende a crear tools, resources y prompts, probarlos con MCP Inspector y desplegarlos.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "advanced",
    readTime: "15 min",
    estimatedMinutes: 15,
    subcategory: "tools",
    learningPaths: ["ai-engineer"],
    prerequisites: ["instalar-mcp"],
    objectives: [
      "Crear un servidor MCP desde cero con TypeScript y @modelcontextprotocol/sdk",
      "Definir tools con esquemas Zod para validación de parámetros",
      "Exponer resources y resource templates",
      "Probar el servidor con MCP Inspector",
      "Configurar el servidor en OpenCode y publicarlo",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "MCP",
      "Tutorial",
      "Node.js",
      "TypeScript",
      "Servidor",
      "Desarrollo",
      "SDK",
    ],
  },
  // ── Clientes MCP ──────────────────────────────────────────────────────
  {
    id: "clientes-mcp",
    slug: "clientes-mcp",
    type: "article",
    title: "Elige tu cliente MCP: comparativa de agentes compatibles",
    description:
      "Comparativa de OpenCode, Claude Code, Cursor, Windsurf, Continue.dev y Cline. Formato de configuración, pros/cons y matriz de decisión según tu stack.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "intermediate",
    readTime: "10 min",
    estimatedMinutes: 10,
    learningPaths: ["ai-engineer"],
    prerequisites: ["instalar-mcp"],
    objectives: [
      "Conocer los 6 clientes MCP principales del ecosistema",
      "Entender las diferencias entre clientes CLI y de IDE",
      "Saber qué formato de configuración usa cada uno",
      "Elegir el cliente adecuado según tu stack y necesidades",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "MCP",
      "Comparativa",
      "OpenCode",
      "Claude Code",
      "Cursor",
      "Windsurf",
      "Continue.dev",
      "Cline",
      "Herramientas",
    ],
  },
  // ── Seguridad MCP ─────────────────────────────────────────────────────
  {
    id: "seguridad-mcp",
    slug: "seguridad-mcp",
    type: "article",
    title: "Seguridad en MCP: cómo auditar y proteger tus servidores",
    description:
      "Guía de seguridad para servidores MCP: modelo de amenazas, auditoría de código, buenas prácticas de configuración, sandboxing y lista de verificación.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "intermediate",
    readTime: "10 min",
    estimatedMinutes: 10,
    learningPaths: ["ai-engineer"],
    prerequisites: ["instalar-mcp"],
    objectives: [
      "Entender el modelo de amenazas de los servidores MCP",
      "Aprender a auditar un servidor MCP antes de instalarlo",
      "Aplicar buenas prácticas de configuración y tokens mínimos",
      "Aislar servidores con sandboxing (Docker, Deno)",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["MCP", "Seguridad", "Tokens", "Permisos", "Auditoría", "Sandbox"],
  },
  // ── Frameworks de agentes ─────────────────────────────────────────────
  {
    id: "frameworks-agentes",
    slug: "frameworks-agentes",
    type: "article",
    title:
      "Frameworks de agentes de IA: LangChain, CrewAI, OpenAI Agents SDK y más",
    description:
      "Comparativa de los 6 principales frameworks para construir agentes de IA: LangChain/LangGraph, CrewAI, OpenAI Agents SDK, Anthropic Claude Agent, AutoGPT y Phidata. Código mínimo de cada uno.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "intermediate",
    readTime: "12 min",
    estimatedMinutes: 12,
    learningPaths: ["ai-engineer"],
    prerequisites: ["ai-project"],
    objectives: [
      "Conocer los 6 frameworks principales para agentes de IA",
      "Entender cuándo usar un framework vs raw LLM",
      "Ver código mínimo de cada framework",
      "Elegir el framework adecuado según el caso de uso",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Agentes",
      "Frameworks",
      "LangChain",
      "CrewAI",
      "OpenAI",
      "Anthropic",
      "Orquestación",
      "IA",
    ],
  },
  // ── Plugins de editor ─────────────────────────────────────────────────
  {
    id: "plugins-ia-editor",
    slug: "plugins-ia-editor",
    type: "article",
    title: "Plugins de editor para IA: VS Code, JetBrains y más",
    description:
      "Catálogo de plugins de IA para editores de código: GitHub Copilot, Supermaven, Continue.dev, Cody, Cline, Tabnine y Codeium. Comparativa de precios, modelos y compatibilidad MCP.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "beginner",
    readTime: "10 min",
    estimatedMinutes: 10,
    learningPaths: ["ai-engineer"],
    prerequisites: ["opencode"],
    objectives: [
      "Conocer los plugins de IA más populares para editores",
      "Entender las categorías: autocompletado, chat, agentes, review",
      "Saber qué plugins soportan MCP",
      "Elegir el plugin adecuado según perfil y presupuesto",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Plugins",
      "VS Code",
      "Editor",
      "Cursor",
      "Continue.dev",
      "Cody",
      "Copilot",
      "Herramientas",
    ],
  },
  // ── Ollama MCP ────────────────────────────────────────────────────────
  {
    id: "ollama-mcp",
    slug: "ollama-mcp",
    type: "tutorial",
    title: "Ollama + MCP: modelos locales con herramientas",
    description:
      "Guía para usar Ollama con el ecosistema MCP. Configura modelos locales en OpenCode, Continue.dev y Cline, y ejecuta herramientas sin depender de la nube.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "intermediate",
    readTime: "8 min",
    estimatedMinutes: 8,
    learningPaths: ["ai-engineer"],
    prerequisites: ["instalar-mcp"],
    objectives: [
      "Configurar Ollama como backend de modelos locales",
      "Conectar Ollama con OpenCode, Continue.dev y Cline",
      "Ejecutar MCPs con modelos locales",
      "Conocer los mejores modelos para tool calling local",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Ollama",
      "MCP",
      "Local",
      "Modelos",
      "OpenCode",
      "Continue.dev",
      "Cline",
      "Tutorial",
    ],
  },
  // ── RAG con MCP ─────────────────────────────────────────────────────
  {
    id: "rag-con-mcp",
    slug: "rag-con-mcp",
    type: "tutorial",
    title: "RAG con MCP: recuperación de información para tu IA",
    description:
      "Implementa Retrieval Augmented Generation usando servidores MCP. Aprende a ingestar documentación con Filesystem MCP, persistir contexto con Memory MCP y construir un asistente que conoce tu código.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "advanced",
    readTime: "10 min",
    estimatedMinutes: 10,
    learningPaths: ["ai-engineer"],
    prerequisites: ["instalar-mcp", "ai-project"],
    objectives: [
      "Entender el pipeline RAG: ingest, store, retrieve, generate",
      "Usar Filesystem MCP y Memory MCP para RAG",
      "Construir un asistente que analiza documentación y responde preguntas",
      "Conocer estrategias de chunking y limitaciones",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "RAG",
      "MCP",
      "Memoria",
      "Filesystem",
      "Búsqueda",
      "Documentación",
      "Asistente",
      "Tutorial",
    ],
  },
  // ── Agentes en paralelo ──────────────────────────────────────────────
  {
    id: "agentes-paralelo",
    slug: "agentes-paralelo",
    type: "tutorial",
    title: "Cómo lanzar varios agentes en paralelo",
    description:
      "Aprende a dividir tareas complejas entre múltiples agentes que trabajan simultáneamente. Multiplica la velocidad de desarrollo sin sacrificar calidad.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-violet-500",
    level: "intermediate",
    readTime: "12 min",
    estimatedMinutes: 12,
    learningPaths: ["ai-engineer"],
    prerequisites: ["opencode"],
    objectives: [
      "Entender cuándo y cómo usar agentes en paralelo",
      "Aprender a dividir el trabajo sin conflictos entre archivos",
      "Escribir prompts efectivos para subagentes",
      "Conocer los 3 patrones principales: componentes, refactor, feature completa",
      "Evitar errores comunes del paralelismo",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Agentes",
      "Paralelo",
      "Task",
      "OpenCode",
      "Productividad",
      "Orquestación",
      "Tutorial",
    ],
  },
  // ── New language tutorials ─────────────────────────────────────────────────
  {
    id: "javascript",
    slug: "javascript",
    type: "tutorial",
    title: "JavaScript: cero a avanzado",
    description:
      "Tutorial completo de JavaScript: fundamentos, funciones, arrays, DOM, asincronía con Promises y async/await, ES6+ y 5 ejercicios prácticos.",
    categoryId: "javascript",
    category: "JavaScript",
    categoryColor: "bg-yellow-500",
    level: "beginner",
    readTime: "90 min",
    estimatedMinutes: 90,
    subcategory: "languages",
    learningPaths: ["fullstack", "frontend", "backend"],
    prerequisites: [],
    objectives: [
      "Dominar variables, tipos y operadores de JavaScript",
      "Usar funciones, closures y scope correctamente",
      "Manipular arrays y objetos con métodos avanzados",
      "Manejar el DOM y eventos del navegador",
      "Trabajar con Promises y async/await",
      "Usar características modernas de ES6+",
    ],
    publishedAt: "2026-06-24",
    featured: true,
    tags: ["JavaScript", "frontend", "backend", "fullstack", "async", "DOM"],
  },
  {
    id: "python",
    slug: "python",
    type: "tutorial",
    title: "Python: cero a avanzado",
    description:
      "Tutorial completo de Python: sintaxis, estructuras de datos, POO, módulos, automatización y 5 ejercicios prácticos.",
    categoryId: "python",
    category: "Python",
    categoryColor: "bg-sky-500",
    level: "beginner",
    readTime: "85 min",
    estimatedMinutes: 85,
    subcategory: "languages",
    learningPaths: ["backend", "ai-engineer"],
    prerequisites: [],
    objectives: [
      "Manejar variables, tipos y control de flujo en Python",
      "Usar listas, diccionarios, sets y tuples",
      "Aplicar programación orientada a objetos",
      "Importar y usar módulos de la librería estándar",
      "Crear scripts de automatización reales",
    ],
    publishedAt: "2026-06-24",
    featured: true,
    tags: ["Python", "backend", "automatización", "POO", "scripts"],
  },
  {
    id: "java",
    slug: "java",
    type: "tutorial",
    title: "Java: cero a avanzado",
    description:
      "Tutorial completo de Java: fundamentos, POO, colecciones, manejo de errores, Streams y un proyecto backend real.",
    categoryId: "java",
    category: "Java",
    categoryColor: "bg-orange-600",
    level: "beginner",
    readTime: "80 min",
    estimatedMinutes: 80,
    subcategory: "languages",
    learningPaths: ["backend"],
    prerequisites: [],
    objectives: [
      "Entender la sintaxis y tipos de Java",
      "Aplicar POO: encapsulación, herencia e interfaces",
      "Usar colecciones: ArrayList, HashMap y HashSet",
      "Manejar excepciones correctamente",
      "Programación funcional básica con Streams",
    ],
    publishedAt: "2026-06-24",
    featured: true,
    tags: ["Java", "backend", "POO", "Streams", "colecciones"],
  },
  // ── Java POO deep dive ─────────────────────────────────────────────────────
  {
    id: "java-poo",
    slug: "java-poo",
    type: "tutorial",
    title: "Java POO: objetos, herencia e interfaces",
    description:
      "Profundiza en la programación orientada a objetos de Java: encapsulación, herencia, interfaces funcionales, records, clases selladas, polimorfismo y patrones de diseño con ejemplos prácticos.",
    categoryId: "java",
    category: "Java",
    categoryColor: "bg-orange-600",
    level: "intermediate",
    readTime: "40 min",
    estimatedMinutes: 40,
    subcategory: "languages",
    learningPaths: ["backend"],
    prerequisites: ["java"],
    objectives: [
      "Dominar encapsulación con getters y copias defensivas",
      "Aplicar herencia y polimorfismo correctamente",
      "Usar interfaces funcionales con lambdas",
      "Modelar datos inmutables con records",
      "Restringir jerarquías con clases selladas",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Java",
      "POO",
      "Herencia",
      "Records",
      "Sealed",
      "Polimorfismo",
      "Backend",
    ],
  },
  // ── Spring Boot ────────────────────────────────────────────────────────────
  {
    id: "java-spring",
    slug: "java-spring",
    type: "tutorial",
    title: "Spring Boot: APIs REST con Java",
    description:
      "Crea APIs REST profesionales con Spring Boot 3: controladores, servicios, JPA, repositorios, DTOs, validación, configuración por perfiles y manejo global de errores.",
    categoryId: "java",
    category: "Java",
    categoryColor: "bg-orange-600",
    level: "advanced",
    readTime: "50 min",
    estimatedMinutes: 50,
    subcategory: "frameworks",
    learningPaths: ["backend"],
    prerequisites: ["java", "java-poo"],
    objectives: [
      "Crear proyectos Spring Boot con Initializr",
      "Implementar REST controllers con validación",
      "Diseñar la capa de servicios con inyección de dependencias",
      "Usar Spring Data JPA con repositorios y entidades",
      "Aplicar DTOs y manejador global de errores",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["Java", "Spring Boot", "REST", "JPA", "Backend", "API", "DTO"],
  },
  // ── HTML y CSS ─────────────────────────────────────────────────────────────
  {
    id: "html-css",
    slug: "html-css",
    type: "tutorial",
    title: "HTML y CSS: fundamentos del desarrollo web",
    description:
      "Aprende los pilares de la web: HTML semántico, CSS selectores, Box Model, Flexbox, CSS Grid, diseño responsive con media queries y un proyecto práctico de tarjeta de perfil.",
    categoryId: "html-css",
    category: "HTML y CSS",
    categoryColor: "bg-orange-500",
    level: "beginner",
    readTime: "55 min",
    estimatedMinutes: 55,
    subcategory: "languages",
    learningPaths: ["frontend"],
    prerequisites: [],
    objectives: [
      "Escribir HTML semántico y accesible",
      "Aplicar CSS con selectores y cascada",
      "Maquetar con Flexbox y CSS Grid",
      "Diseñar interfaces responsive sin frameworks",
      "Construir un proyecto web completo desde cero",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["HTML", "CSS", "Frontend", "Flexbox", "Grid", "Responsive", "Web"],
  },
  // ── Testing Frontend ───────────────────────────────────────────────────────
  {
    id: "testing-frontend",
    slug: "testing-frontend",
    type: "tutorial",
    title: "Testing frontend con Vitest, Testing Library y Playwright",
    description:
      "Aprende a testear aplicaciones frontend: tests unitarios con Vitest, tests de componentes con Testing Library, mocks, tests de integración, E2E con Playwright y cobertura de código.",
    categoryId: "testing",
    category: "Testing",
    categoryColor: "bg-rose-500",
    level: "intermediate",
    readTime: "50 min",
    estimatedMinutes: 50,
    subcategory: "tools",
    learningPaths: ["frontend"],
    prerequisites: ["javascript", "react-framework"],
    objectives: [
      "Escribir tests unitarios con Vitest",
      "Testear componentes React con Testing Library",
      "Mockear APIs y módulos externos",
      "Crear tests de integración de flujos completos",
      "Automatizar tests E2E con Playwright",
    ],
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Testing",
      "Vitest",
      "Testing Library",
      "Playwright",
      "Frontend",
      "Calidad",
      "E2E",
    ],
  },
  // ── Framework tutorials ────────────────────────────────────────────────────
  {
    id: "react-framework",
    slug: "react-framework",
    type: "tutorial",
    title: "React: componentes a apps",
    description:
      "Aprende React moderno con hooks, routing, Context API y optimización de rendimiento. Incluye proyecto dashboard completo.",
    categoryId: "react",
    category: "React",
    categoryColor: "bg-cyan-500",
    level: "intermediate",
    readTime: "70 min",
    estimatedMinutes: 70,
    subcategory: "frameworks",
    learningPaths: ["fullstack", "frontend"],
    prerequisites: ["javascript"],
    objectives: [
      "Crear componentes funcionales con props y children",
      "Usar hooks: useState, useEffect, useMemo, useCallback",
      "Implementar routing con React Router",
      "Gestionar estado global con Context API",
      "Optimizar rendimiento con memoización",
    ],
    publishedAt: "2026-06-24",
    featured: true,
    tags: ["React", "frontend", "hooks", "Context API", "rendimiento"],
  },
  {
    id: "node-express",
    slug: "node-express",
    type: "tutorial",
    title: "Node.js + Express: APIs REST",
    description:
      "Construye APIs REST completas con Node.js y Express: routing, middlewares, JWT, validación y arquitectura por capas.",
    categoryId: "nodejs",
    category: "Node.js",
    categoryColor: "bg-green-600",
    level: "intermediate",
    readTime: "75 min",
    estimatedMinutes: 75,
    subcategory: "frameworks",
    learningPaths: ["fullstack", "backend"],
    prerequisites: ["javascript"],
    objectives: [
      "Configurar un servidor Express con routing modular",
      "Implementar middlewares de seguridad y validación",
      "Crear APIs REST completas (GET/POST/PUT/DELETE)",
      "Añadir autenticación JWT",
      "Estructurar el proyecto con controllers y services",
    ],
    publishedAt: "2026-06-24",
    featured: true,
    tags: ["Node.js", "Express", "backend", "APIs", "JWT", "arquitectura"],
  },
  {
    id: "nextjs-framework",
    slug: "nextjs-framework",
    type: "tutorial",
    title: "Next.js: apps fullstack",
    description:
      "Domina Next.js con App Router, SSR, SSG, ISR, API Routes y optimización avanzada de rendimiento.",
    categoryId: "nextjs",
    category: "Next.js",
    categoryColor: "bg-black",
    level: "advanced",
    readTime: "80 min",
    estimatedMinutes: 80,
    subcategory: "frameworks",
    learningPaths: ["fullstack", "frontend"],
    prerequisites: ["react-framework"],
    objectives: [
      "Entender SSR, CSR, SSG e ISR en profundidad",
      "Usar App Router con layouts y páginas dinámicas",
      "Crear API Routes integradas en el proyecto",
      "Optimizar performance con caching y lazy loading",
      "Construir una aplicación fullstack completa",
    ],
    publishedAt: "2026-06-24",
    featured: true,
    tags: ["Next.js", "fullstack", "SSR", "SSG", "rendimiento", "frontend"],
  },
  // ── Frontend avanzado ───────────────────────────────────────────────────────
  {
    id: "css-avanzado",
    slug: "css-avanzado",
    type: "tutorial",
    title: "CSS avanzado: animaciones y layouts modernos",
    description:
      "Domina CSS moderno: transiciones, transformaciones, keyframes, container queries, el selector :has(), custom properties y técnicas para animar con rendimiento.",
    categoryId: "css",
    category: "CSS",
    categoryColor: "bg-blue-400",
    level: "intermediate",
    readTime: "55 min",
    estimatedMinutes: 55,
    subcategory: "languages",
    learningPaths: ["frontend"],
    prerequisites: ["html-css"],
    objectives: [
      "Dominar transiciones, transformaciones y keyframes",
      "Construir layouts modernos con container queries y :has()",
      "Crear temas escalables con custom properties",
      "Optimizar animaciones animando solo transform y opacity",
      "Escribir CSS mantenible con funciones modernas",
    ],
    publishedAt: "2026-08-03",
    featured: true,
    tags: ["CSS", "Animaciones", "Keyframes", "Custom Properties", "Frontend"],
  },
  {
    id: "javascript-avanzado",
    slug: "javascript-avanzado",
    type: "tutorial",
    title: "JavaScript moderno: asíncrono y APIs del navegador",
    description:
      "Lleva tu JavaScript al siguiente nivel: promesas en profundidad, async/await, fetch y consumo de APIs, módulos ES, DOM avanzado y las APIs del navegador que más se usan.",
    categoryId: "javascript",
    category: "JavaScript",
    categoryColor: "bg-yellow-500",
    level: "intermediate",
    readTime: "55 min",
    estimatedMinutes: 55,
    subcategory: "languages",
    learningPaths: ["frontend", "fullstack"],
    prerequisites: ["javascript"],
    objectives: [
      "Manejar promesas y async/await en profundidad",
      "Consumir APIs con fetch y cancelar peticiones con AbortController",
      "Usar módulos ES y import dinámico",
      "Aplicar event delegation e IntersectionObserver",
      "Trabajar con localStorage, URL, Clipboard e Intl",
    ],
    publishedAt: "2026-08-03",
    featured: true,
    tags: ["JavaScript", "Async", "Fetch", "DOM", "Módulos", "APIs"],
  },
  {
    id: "typescript-avanzado",
    slug: "typescript-avanzado",
    type: "tutorial",
    title: "TypeScript avanzado: tipos, generics y utilidades",
    description:
      "Domina el sistema de tipos de TypeScript: narrowing, uniones discriminadas, generics con constraints, utility types, mapped types y tipado avanzado en React.",
    categoryId: "typescript",
    category: "TypeScript",
    categoryColor: "bg-blue-500",
    level: "advanced",
    readTime: "55 min",
    estimatedMinutes: 55,
    subcategory: "languages",
    learningPaths: ["frontend", "backend", "fullstack"],
    prerequisites: ["typescript"],
    objectives: [
      "Aplicar narrowing, type guards y uniones discriminadas",
      "Diseñar generics avanzados con constraints",
      "Componer tipos con utility types y mapped types",
      "Tipar hooks, contextos y props de React correctamente",
      "Configurar un tsconfig estricto",
    ],
    publishedAt: "2026-08-03",
    featured: true,
    tags: ["TypeScript", "Generics", "Utility Types", "Tipado", "React"],
  },
  {
    id: "estado-global",
    slug: "estado-global",
    type: "tutorial",
    title: "Estado global y data fetching",
    description:
      "Gestiona estado complejo y datos remotos como un profesional: Context API avanzado, Zustand con slices y persistencia, y React Query para caching, mutations e invalidación.",
    categoryId: "state-management",
    category: "Estado global",
    categoryColor: "bg-fuchsia-500",
    level: "advanced",
    readTime: "60 min",
    estimatedMinutes: 60,
    subcategory: "frameworks",
    learningPaths: ["frontend", "fullstack"],
    prerequisites: ["react-framework"],
    objectives: [
      "Decidir cuándo usar Context, Zustand o React Query",
      "Crear stores con Zustand, slices y middleware persist",
      "Cachear datos con React Query y controlar su ciclo de vida",
      "Invalidar y actualizar caché tras mutations",
      "Integrar data fetching en aplicaciones Next.js",
    ],
    publishedAt: "2026-08-03",
    featured: true,
    tags: ["React", "Zustand", "React Query", "Estado", "Data Fetching"],
  },
  {
    id: "rendimiento-frontend",
    slug: "rendimiento-frontend",
    type: "tutorial",
    title: "Rendimiento frontend: Core Web Vitals y optimización",
    description:
      "Optimiza tus apps para que carguen y respondan rápido: Core Web Vitals, Lighthouse, code splitting, imágenes, caching, memoización y cómo eliminar el CLS.",
    categoryId: "performance",
    category: "Rendimiento",
    categoryColor: "bg-amber-500",
    level: "advanced",
    readTime: "60 min",
    estimatedMinutes: 60,
    subcategory: "tools",
    learningPaths: ["frontend", "fullstack"],
    prerequisites: ["react-framework", "nextjs-framework"],
    objectives: [
      "Medir y mejorar LCP, INP y CLS",
      "Auditar apps con Lighthouse y DevTools",
      "Aplicar code splitting, lazy loading y prefetch",
      "Optimizar imágenes y gestionar el caché",
      "Usar memoización con criterio y evitar CLS",
    ],
    publishedAt: "2026-08-03",
    featured: true,
    tags: ["Rendimiento", "Core Web Vitals", "Lighthouse", "Optimización"],
  },
  {
    id: "accesibilidad",
    slug: "accesibilidad",
    type: "tutorial",
    title: "Accesibilidad web: WCAG, ARIA y buenas prácticas",
    description:
      "Construye webs accesibles para todos: principios WCAG 2.2, HTML semántico, ARIA con criterio, formularios y navegación por teclado accesibles, contraste y testing con axe.",
    categoryId: "accesibilidad",
    category: "Accesibilidad",
    categoryColor: "bg-violet-500",
    level: "intermediate",
    readTime: "50 min",
    estimatedMinutes: 50,
    subcategory: "tools",
    learningPaths: ["frontend", "fullstack"],
    prerequisites: ["html-css"],
    objectives: [
      "Entender los principios POUR y los niveles de WCAG 2.2",
      "Construir con HTML semántico y landmarks",
      "Usar ARIA solo cuando es necesario",
      "Crear formularios y modales accesibles por teclado",
      "Automatizar tests de accesibilidad con axe",
    ],
    publishedAt: "2026-08-03",
    featured: true,
    tags: ["Accesibilidad", "a11y", "WCAG", "ARIA", "Frontend"],
  },
  {
    id: "json-formatter",
    slug: "json-formatter",
    type: "tool",
    title: "Formateador de JSON",
    description:
      "Formatea, minifica y valida JSON al instante. Sin servidores, todo en tu navegador.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-amber-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: ["fullstack", "backend", "frontend"],
    prerequisites: [],
    publishedAt: "2026-06-25",
    featured: true,
    tags: ["JSON", "Formato", "Validación", "Herramienta"],
  },
  {
    id: "base64",
    slug: "base64",
    type: "tool",
    title: "Codificador Base64",
    description:
      "Codifica y decodifica texto en Base64 al instante. Útil para tokens, imágenes y APIs.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-sky-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: ["fullstack", "backend"],
    prerequisites: [],
    publishedAt: "2026-06-25",
    featured: false,
    tags: ["Base64", "Encoding", "JWT", "API", "Herramienta"],
  },
  {
    id: "regex-tester",
    slug: "regex-tester",
    type: "tool",
    title: "Tester de Regex",
    description:
      "Prueba expresiones regulares en tiempo real con resaltado de coincidencias y ejemplos predefinidos.",
    categoryId: "dev-tools",
    category: "Dev Tools",
    categoryColor: "bg-rose-500",
    level: "intermediate",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: ["fullstack", "backend", "frontend"],
    prerequisites: [],
    publishedAt: "2026-06-25",
    featured: true,
    tags: ["Regex", "Expresiones regulares", "Herramienta", "Validación"],
  },
  {
    id: "color-tool",
    slug: "color-tool",
    type: "tool",
    title: "Conversor de colores",
    description:
      "Convierte entre HEX, RGB y HSL. Selector interactivo, sliders y paletas predefinidas.",
    categoryId: "design",
    category: "Diseño",
    categoryColor: "bg-pink-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: ["frontend"],
    prerequisites: [],
    publishedAt: "2026-06-25",
    featured: false,
    tags: ["Color", "CSS", "Diseño", "HEX", "RGB", "HSL", "Herramienta"],
  },
  {
    id: "password",
    slug: "password",
    type: "tool",
    title: "Generador de contraseñas",
    description:
      "Crea contraseñas seguras y aleatorias con control total sobre longitud y tipos de caracteres.",
    categoryId: "security",
    category: "Seguridad",
    categoryColor: "bg-violet-500",
    level: "beginner",
    readTime: "Uso libre",
    estimatedMinutes: 0,
    learningPaths: ["backend"],
    prerequisites: [],
    objectives: [
      "Generar contraseñas seguras configurables",
      "Entender los requisitos de una contraseña robusta",
    ],
    publishedAt: "2026-06-23",
    featured: true,
    tags: ["Seguridad", "Privacidad", "Contraseñas", "seguridad"],
  },
  // ── VS Code ────────────────────────────────────────────────────────────
  {
    id: "vscode-config",
    slug: "vscode-config",
    type: "article",
    title: "Personaliza VS Code como un pro",
    description:
      "Guía completa de configuración de VS Code: settings.json, keybindings, temas, perfiles, workspace vs user settings y Settings Sync.",
    categoryId: "resources",
    category: "Recursos",
    categoryColor: "bg-amber-400",
    level: "beginner",
    readTime: "8 min",
    estimatedMinutes: 8,
    learningPaths: ["fullstack", "frontend", "backend"],
    prerequisites: [],
    objectives: [
      "Configurar settings.json con ajustes esenciales",
      "Personalizar tema, colores y tipografía",
      "Crear keybindings personalizados",
      "Entender la diferencia entre User y Workspace settings",
      "Usar perfiles para distintos roles",
      "Activar Settings Sync para múltiples máquinas",
    ],
    publishedAt: "2026-07-29",
    featured: true,
    tags: [
      "VS Code",
      "Configuración",
      "Editor",
      "Personalización",
      "Productividad",
      "settings.json",
    ],
  },
  {
    id: "vscode-extensions",
    slug: "vscode-extensions",
    type: "article",
    title: "Extensiones imprescindibles para VS Code",
    description:
      "Catálogo completo de extensiones de VS Code organizadas por categoría: linting, Git, lenguajes, productividad, temas, utilidades, y recomendaciones por perfil.",
    categoryId: "resources",
    category: "Recursos",
    categoryColor: "bg-amber-400",
    level: "beginner",
    readTime: "10 min",
    estimatedMinutes: 10,
    learningPaths: ["fullstack", "frontend", "backend"],
    prerequisites: [],
    objectives: [
      "Conocer las extensiones esenciales para cada categoría",
      "Saber qué extensiones evitar y por qué",
      "Elegir las extensiones adecuadas según tu perfil",
      "Optimizar el rendimiento evitando extensiones innecesarias",
    ],
    publishedAt: "2026-07-29",
    featured: true,
    tags: [
      "VS Code",
      "Extensiones",
      "ESLint",
      "GitLens",
      "GitHub Copilot",
      "Prettier",
      "Productividad",
    ],
  },
  // ── Bases de datos ────────────────────────────────────────────────────
  {
    id: "database-intro",
    slug: "database-intro",
    type: "article",
    title: "¿Qué es una base de datos?",
    description:
      "Introducción a las bases de datos: qué son, para qué sirven, funcionalidades clave, componentes, historia y tipos principales (relacionales, NoSQL, clave-valor, grafos).",
    categoryId: "sql",
    category: "SQL",
    categoryColor: "bg-blue-600",
    level: "beginner",
    readTime: "6 min",
    estimatedMinutes: 6,
    learningPaths: ["fullstack", "backend"],
    prerequisites: [],
    objectives: [
      "Entender qué es una base de datos y su propósito",
      "Conocer las funcionalidades principales (CRUD, ACID, concurrencia)",
      "Identificar los diferentes tipos de bases de datos",
      "Conocer la evolución histórica de las bases de datos",
    ],
    publishedAt: "2026-07-29",
    featured: true,
    tags: ["Base de datos", "SQL", "NoSQL", "Introducción", "Arquitectura"],
  },
  {
    id: "sql-vs-nosql",
    slug: "sql-vs-nosql",
    type: "article",
    title: "SQL vs NoSQL: ¿cuál elegir?",
    description:
      "Comparativa completa entre bases de datos SQL y NoSQL: modelos, escalabilidad, ACID vs BASE, casos de uso, y cómo elegir la tecnología adecuada para cada proyecto.",
    categoryId: "sql",
    category: "SQL",
    categoryColor: "bg-blue-600",
    level: "beginner",
    readTime: "8 min",
    estimatedMinutes: 8,
    learningPaths: ["fullstack", "backend"],
    prerequisites: [],
    objectives: [
      "Entender las diferencias fundamentales entre SQL y NoSQL",
      "Conocer los 4 tipos de bases de datos NoSQL",
      "Saber cuándo usar cada tipo según el proyecto",
      "Entender el concepto de persistencia políglota",
    ],
    publishedAt: "2026-07-29",
    featured: true,
    tags: ["SQL", "NoSQL", "Comparativa", "Base de datos", "Arquitectura"],
  },
  {
    id: "sql-basics",
    slug: "sql-basics",
    type: "tutorial",
    title: "SQL desde cero",
    description:
      "Aprende SQL desde lo más básico hasta técnicas avanzadas: SELECT, JOINs, GROUP BY, subconsultas, CTEs y ejercicios prácticos con solución.",
    categoryId: "sql",
    category: "SQL",
    categoryColor: "bg-blue-600",
    level: "beginner",
    readTime: "15 min",
    estimatedMinutes: 15,
    learningPaths: ["fullstack", "backend", "frontend"],
    prerequisites: [],
    objectives: [
      "Escribir consultas SELECT con filtros y ordenación",
      "Usar JOINs para combinar tablas",
      "Aplicar funciones de agregación con GROUP BY",
      "Crear subconsultas y CTEs",
      "Resolver 8 ejercicios prácticos",
    ],
    publishedAt: "2026-07-29",
    featured: true,
    tags: ["SQL", "SELECT", "JOIN", "GROUP BY", "CTE", "Tutorial"],
  },
  {
    id: "mysql-guide",
    slug: "mysql-guide",
    type: "tutorial",
    title: "MySQL: instalación y primeros pasos",
    description:
      "Guía completa de MySQL: instalación, tipos de datos, CREATE TABLE, ENGINEs, herramientas visuales y ejercicios prácticos con esquema e-commerce.",
    categoryId: "mysql",
    category: "MySQL",
    categoryColor: "bg-orange-500",
    level: "beginner",
    readTime: "10 min",
    estimatedMinutes: 10,
    learningPaths: ["fullstack", "backend"],
    prerequisites: ["sql-basics"],
    objectives: [
      "Instalar MySQL en macOS, Docker y Linux",
      "Crear bases de datos, usuarios y tablas",
      "Conocer los tipos de datos específicos de MySQL",
      "Usar herramientas como Workbench y TablePlus",
      "Resolver ejercicios con un schema completo",
    ],
    publishedAt: "2026-07-29",
    featured: true,
    tags: ["MySQL", "Instalación", "SQL", "Base de datos", "Workbench"],
  },
  {
    id: "postgresql-guide",
    slug: "postgresql-guide",
    type: "tutorial",
    title: "PostgreSQL: el gigante open-source",
    description:
      "Tutorial completo de PostgreSQL: instalación, tipos exclusivos (JSONB, ARRAY, TSVECTOR), full-text search, índices, EXPLAIN ANALYZE y ejercicios prácticos.",
    categoryId: "postgresql",
    category: "PostgreSQL",
    categoryColor: "bg-blue-800",
    level: "intermediate",
    readTime: "12 min",
    estimatedMinutes: 12,
    learningPaths: ["fullstack", "backend"],
    prerequisites: ["sql-basics"],
    objectives: [
      "Instalar PostgreSQL y usar psql",
      "Trabajar con tipos exclusivos: JSONB, ARRAY, TSVECTOR",
      "Implementar full-text search nativo",
      "Analizar rendimiento con EXPLAIN ANALYZE",
      "Resolver ejercicios con características avanzadas",
    ],
    publishedAt: "2026-07-29",
    featured: true,
    tags: [
      "PostgreSQL",
      "JSONB",
      "Full-text search",
      "Índices",
      "SQL",
      "Base de datos",
    ],
  },
  {
    id: "mongodb-guide",
    slug: "mongodb-guide",
    type: "tutorial",
    title: "MongoDB: la revolución NoSQL",
    description:
      "Tutorial de MongoDB desde cero: documentos BSON, CRUD, operadores de query, aggregation pipeline, índices, diferencias con SQL y ejercicios prácticos.",
    categoryId: "mongodb",
    category: "MongoDB",
    categoryColor: "bg-green-600",
    level: "beginner",
    readTime: "12 min",
    estimatedMinutes: 12,
    learningPaths: ["fullstack", "backend"],
    prerequisites: [],
    objectives: [
      "Instalar MongoDB y usar mongosh",
      "Realizar operaciones CRUD con documentos",
      "Usar operadores de query avanzados",
      "Construir pipelines de agregación",
      "Crear índices y analizar rendimiento",
    ],
    publishedAt: "2026-07-29",
    featured: true,
    tags: [
      "MongoDB",
      "NoSQL",
      "CRUD",
      "Aggregation",
      "Documentos",
      "Base de datos",
    ],
  },
  {
    id: "supabase-guide",
    slug: "supabase-guide",
    type: "tutorial",
    title: "Supabase: backend como servicio con PostgreSQL",
    description:
      "Guía de Supabase: crear proyecto, SQL Editor, Auth con RLS policies, Realtime subscriptions, Storage, Edge Functions y ejercicios prácticos.",
    categoryId: "supabase",
    category: "Supabase",
    categoryColor: "bg-emerald-500",
    level: "intermediate",
    readTime: "10 min",
    estimatedMinutes: 10,
    learningPaths: ["fullstack", "backend"],
    prerequisites: ["postgresql-guide", "sql-basics"],
    objectives: [
      "Crear un proyecto en Supabase",
      "Definir tablas con SQL Editor y RLS policies",
      "Implementar autenticación con Auth",
      "Usar Realtime para suscripciones en vivo",
      "Subir archivos con Storage policies",
      "Desplegar Edge Functions",
    ],
    publishedAt: "2026-07-29",
    featured: true,
    tags: [
      "Supabase",
      "PostgreSQL",
      "Auth",
      "RLS",
      "Realtime",
      "Backend",
      "BaaS",
    ],
  },
  {
    id: "sql-builder-guide",
    slug: "sql-builder-guide",
    type: "article",
    title: "Guía del Constructor SQL",
    description:
      "Aprende a usar el Constructor SQL interactivo: parsea DDL, construye consultas visualmente y genera SELECT sin escribir SQL a mano. Incluye JOINs automáticos.",
    categoryId: "sql",
    category: "SQL",
    categoryColor: "bg-blue-600",
    level: "beginner",
    readTime: "5 min",
    estimatedMinutes: 5,
    learningPaths: ["fullstack", "backend", "frontend"],
    prerequisites: [],
    objectives: [
      "Entender cómo parsea DDL el constructor",
      "Usar SELECT, WHERE, ORDER BY y GROUP BY visualmente",
      "Aprovechar los JOINs automáticos por clave foránea",
      "Guardar y recuperar consultas con el historial",
    ],
    publishedAt: "2026-07-30",
    featured: true,
    tags: ["SQL", "Constructor", "SELECT", "JOIN", "Herramienta", "Guía"],
  },
  // ── Frontend frameworks ────────────────────────────────────────────────
  {
    id: "angular",
    slug: "angular",
    type: "tutorial",
    title: "Angular: componentes a aplicaciones enterprise",
    description:
      "Aprende Angular moderno con componentes standalone, plantillas con @if/@for, services con inyección de dependencias, HttpClient y routing. El framework completo para aplicaciones enterprise.",
    categoryId: "angular",
    category: "Angular",
    categoryColor: "bg-red-600",
    level: "intermediate",
    readTime: "70 min",
    estimatedMinutes: 70,
    subcategory: "frameworks",
    learningPaths: ["frontend", "fullstack"],
    prerequisites: ["typescript"],
    objectives: [
      "Crear componentes standalone con Angular CLI",
      "Usar plantillas con interpolación, @if, @for y @switch",
      "Implementar services con inyección de dependencias",
      "Consumir APIs con HttpClient",
      "Configurar routing con parámetros y lazy loading",
    ],
    publishedAt: "2026-08-01",
    featured: true,
    tags: [
      "Angular",
      "Frontend",
      "TypeScript",
      "Componentes",
      "SPA",
      "Framework",
    ],
  },
  {
    id: "vue",
    slug: "vue",
    type: "tutorial",
    title: "Vue.js: el framework progresivo",
    description:
      "Domina Vue 3 con Composition API, reactividad con ref/reactive, directivas v-if/v-for/v-model, props y emits, slots, Vue Router y Pinia. Desde cero con Vite.",
    categoryId: "vue",
    category: "Vue",
    categoryColor: "bg-emerald-500",
    level: "intermediate",
    readTime: "60 min",
    estimatedMinutes: 60,
    subcategory: "frameworks",
    learningPaths: ["frontend", "fullstack"],
    prerequisites: ["javascript"],
    objectives: [
      "Crear proyectos Vue 3 con Vite y <script setup>",
      "Dominar la reactividad con ref, reactive y computed",
      "Usar directivas v-if, v-for y v-model",
      "Comunicar componentes con props, emits y slots",
      "Añadir rutas con Vue Router y estado con Pinia",
    ],
    publishedAt: "2026-08-01",
    featured: true,
    tags: [
      "Vue",
      "Frontend",
      "JavaScript",
      "Composition API",
      "Vite",
      "Framework",
    ],
  },
  {
    id: "tailwind-css",
    slug: "tailwind-css",
    type: "tutorial",
    title: "Tailwind CSS: diseño utility-first",
    description:
      "Aprende Tailwind CSS v4: instalación con Vite y Next.js, utilities de spacing y tipografía, Flexbox y Grid, responsive, dark mode, estados y customización con @theme y @layer.",
    categoryId: "tailwind",
    category: "Tailwind CSS",
    categoryColor: "bg-teal-500",
    level: "intermediate",
    readTime: "45 min",
    estimatedMinutes: 45,
    subcategory: "frameworks",
    learningPaths: ["frontend", "fullstack"],
    prerequisites: ["html-css"],
    objectives: [
      "Entender el enfoque utility-first",
      "Instalar Tailwind v4 con Vite y Next.js",
      "Maquetar con Flexbox y Grid utilities",
      "Crear diseños responsive y dark mode",
      "Customizar el tema con @theme y crear componentes con @layer",
    ],
    publishedAt: "2026-08-01",
    featured: true,
    tags: [
      "Tailwind",
      "CSS",
      "Frontend",
      "Utility-first",
      "Responsive",
      "Dark mode",
    ],
  },
  // ── DevOps ─────────────────────────────────────────────────────────────
  {
    id: "docker",
    slug: "docker",
    type: "tutorial",
    title: "Docker: contenedores de cero a producción",
    description:
      "Aprende Docker desde cero: imágenes y contenedores, Dockerfile, build y run, volúmenes, redes y Docker Compose para levantar un stack completo api + base de datos.",
    categoryId: "docker",
    category: "Docker",
    categoryColor: "bg-blue-600",
    level: "intermediate",
    readTime: "50 min",
    estimatedMinutes: 50,
    subcategory: "tools",
    learningPaths: ["backend", "fullstack"],
    prerequisites: ["git"],
    objectives: [
      "Entender la diferencia entre imagen y contenedor",
      "Escribir Dockerfiles eficientes",
      "Construir, etiquetar y ejecutar contenedores",
      "Persistir datos con volúmenes",
      "Orquestar servicios con Docker Compose",
    ],
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["Docker", "Contenedores", "DevOps", "Dockerfile", "Compose"],
  },
  {
    id: "ci-cd",
    slug: "ci-cd",
    type: "tutorial",
    title: "CI/CD con GitHub Actions",
    description:
      "Implementa integración y despliegue continuos con GitHub Actions: workflows, jobs y steps, triggers, build + lint + test, secrets, cache y despliegue automático a producción.",
    categoryId: "ci-cd",
    category: "CI/CD",
    categoryColor: "bg-violet-600",
    level: "intermediate",
    readTime: "45 min",
    estimatedMinutes: 45,
    subcategory: "tools",
    learningPaths: ["backend", "fullstack"],
    prerequisites: ["git"],
    objectives: [
      "Entender los conceptos de CI/CD y GitHub Actions",
      "Escribir workflows con jobs y steps",
      "Automatizar build, lint y test",
      "Usar secrets y cache de dependencias",
      "Desplegar automáticamente con matrices y triggers",
    ],
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["CI/CD", "GitHub Actions", "DevOps", "Pipeline", "Deploy"],
  },
  {
    id: "kubernetes",
    slug: "kubernetes",
    type: "tutorial",
    title: "Kubernetes: orquestación de contenedores",
    description:
      "Domina Kubernetes: arquitectura del cluster, Pods, Deployments con escala y rollback, Services, ConfigMaps y Secrets, e Ingress para exponer tus aplicaciones.",
    categoryId: "kubernetes",
    category: "Kubernetes",
    categoryColor: "bg-blue-700",
    level: "advanced",
    readTime: "55 min",
    estimatedMinutes: 55,
    subcategory: "tools",
    learningPaths: ["backend", "fullstack"],
    prerequisites: ["docker"],
    objectives: [
      "Entender la arquitectura de Kubernetes",
      "Crear y gestionar Pods y Deployments",
      "Exponer servicios con ClusterIP, NodePort y LoadBalancer",
      "Configurar ConfigMaps y Secrets",
      "Usar Ingress y kubectl apply -f",
    ],
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["Kubernetes", "DevOps", "Contenedores", "Pods", "Orquestación"],
  },
  // ── Languages ───────────────────────────────────────────────────────────
  {
    id: "go",
    slug: "go",
    type: "tutorial",
    title: "Go: cero a servidor web",
    description:
      "Aprende Go desde cero: sintaxis y tipos, funciones y errores, structs e interfaces, goroutines y channels, y construye un servidor HTTP con net/http.",
    categoryId: "go",
    category: "Go",
    categoryColor: "bg-cyan-500",
    level: "beginner",
    readTime: "70 min",
    estimatedMinutes: 70,
    subcategory: "languages",
    learningPaths: ["backend"],
    prerequisites: [],
    objectives: [
      "Escribir programas Go con variables y tipos",
      "Crear funciones y manejar errores como valores",
      "Modelar datos con structs e interfaces",
      "Usar goroutines y channels para concurrencia",
      "Construir una API REST con net/http",
    ],
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["Go", "Backend", "Goroutines", "HTTP", "Lenguaje"],
  },
  {
    id: "rust",
    slug: "rust",
    type: "tutorial",
    title: "Rust: memoria segura y rendimiento",
    description:
      "Domina Rust: ownership y borrowing, structs, enums y match, traits, manejo de errores con Result y Option, y crea proyectos CLI con Cargo.",
    categoryId: "rust",
    category: "Rust",
    categoryColor: "bg-orange-700",
    level: "intermediate",
    readTime: "75 min",
    estimatedMinutes: 75,
    subcategory: "languages",
    learningPaths: ["backend", "fullstack"],
    prerequisites: ["c-lang"],
    objectives: [
      "Entender ownership, borrowing y lifetimes",
      "Modelar datos con structs, enums y match",
      "Implementar traits y derive",
      "Manejar errores con Result y Option",
      "Crear y compilar proyectos con Cargo",
    ],
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["Rust", "Sistemas", "Ownership", "Cargo", "Rendimiento"],
  },
  {
    id: "nestjs",
    slug: "nestjs",
    type: "tutorial",
    title: "NestJS: APIs estructuradas con TypeScript",
    description:
      "Crea APIs robustas con NestJS: módulos, controllers, services con inyección de dependencias, DTOs con validación, TypeORM, guards con JWT y documentación con Swagger.",
    categoryId: "nestjs",
    category: "NestJS",
    categoryColor: "bg-red-500",
    level: "advanced",
    readTime: "60 min",
    estimatedMinutes: 60,
    subcategory: "frameworks",
    learningPaths: ["backend", "fullstack"],
    prerequisites: ["typescript", "node-express"],
    objectives: [
      "Estructurar aplicaciones con módulos de NestJS",
      "Crear controllers y services con decoradores",
      "Validar entradas con DTOs y ValidationPipe",
      "Persistir datos con TypeORM",
      "Proteger rutas con guards y JWT",
    ],
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["NestJS", "TypeScript", "Backend", "API", "Decoradores", "Node"],
  },
];

// ── Guide types ───────────────────────────────────────────────────────────────

export interface GuideStep {
  /** Slug of the tutorial included in this guide */
  slug: string;
  /** Whether this step is optional/supplementary */
  optional?: boolean;
}

export interface GuideMeta {
  id: string;
  slug: string;
  title: string;
  description: string;
  categoryId: string;
  category: string;
  categoryColor: string;
  level?: DifficultyLevel;
  readTime: string;
  estimatedMinutes?: number;
  publishedAt: string;
  featured?: boolean;
  tags?: string[];
  /** Top-level branch/domain this guide belongs to */
  branch: GuideBranchId;
  /** Slug of a guide this one builds on (sub-branch) */
  dependsOn?: string;
  /** Branches this framework guide converges (joins). Non-empty → rendered in the convergence band */
  joins?: GuideBranchId[];
  /** Ordered list of tutorials in this guide */
  curriculum: GuideStep[];
}

export type GuideBranchId = "web" | "backend" | "ai" | "systems";

export const GUIDE_BRANCHES: { id: GuideBranchId; labelKey: string }[] = [
  { id: "web", labelKey: "campus.branch.web" },
  { id: "backend", labelKey: "campus.branch.backend" },
  { id: "ai", labelKey: "campus.branch.ai" },
  { id: "systems", labelKey: "campus.branch.systems" },
];

export const allGuides: GuideMeta[] = [
  {
    id: "ruta-opencode",
    slug: "ruta-opencode",
    title: "Ruta OpenCode",
    description:
      "Domina OpenCode de principio a fin: instalación, modelos, MCP, Skills, agentes en paralelo, RAG, frameworks de IA y plugins de editor.",
    categoryId: "opencode",
    category: "OpenCode",
    categoryColor: "bg-emerald-500",
    branch: "ai",
    level: "beginner",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["OpenCode", "MCP", "Skills", "IA", "Guía"],
    curriculum: [
      { slug: "opencode" },
      { slug: "opencode-models" },
      { slug: "instalar-mcp" },
      { slug: "mcp-servers" },
      { slug: "skills-tutorial" },
      { slug: "skills-catalog" },
      { slug: "crear-mcp" },
      { slug: "clientes-mcp" },
      { slug: "seguridad-mcp" },
      { slug: "ollama-mcp" },
      { slug: "rag-con-mcp" },
      { slug: "frameworks-agentes" },
      { slug: "plugins-ia-editor" },
      { slug: "agentes-paralelo" },
      { slug: "ai-project" },
    ],
  },
  {
    id: "ruta-java",
    slug: "ruta-java",
    title: "Ruta Java",
    description:
      "Aprende Java desde cero hasta nivel avanzado: sintaxis, POO, colecciones, Streams, Spring Boot y APIs REST. Ruta completa para desarrolladores backend empresariales.",
    categoryId: "java",
    category: "Java",
    categoryColor: "bg-orange-600",
    branch: "backend",
    level: "beginner",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["Java", "Backend", "POO", "Spring", "API", "Guía"],
    curriculum: [
      { slug: "java" },
      { slug: "java-poo" },
      { slug: "java-spring" },
    ],
  },
  {
    id: "ruta-frontend",
    slug: "ruta-frontend",
    title: "Ruta Frontend Web",
    description:
      "De cero a frontend moderno: HTML y CSS, JavaScript, TypeScript, React, Next.js y testing. Ruta completa para dominar el desarrollo web desde los fundamentos hasta producción.",
    categoryId: "html-css",
    category: "HTML y CSS",
    categoryColor: "bg-orange-500",
    branch: "web",
    level: "beginner",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Frontend",
      "Web",
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Next.js",
      "Testing",
      "Guía",
    ],
    curriculum: [
      { slug: "html-css" },
      { slug: "css-avanzado" },
      { slug: "javascript" },
      { slug: "javascript-avanzado" },
      { slug: "typescript" },
      { slug: "typescript-avanzado" },
      { slug: "react-framework" },
      { slug: "estado-global" },
      { slug: "nextjs-framework" },
      { slug: "rendimiento-frontend" },
      { slug: "accesibilidad" },
      { slug: "testing-frontend" },
      { slug: "tailwind-css" },
    ],
  },
  {
    id: "ruta-c",
    slug: "ruta-c",
    title: "Ruta C",
    description:
      "Aprende C desde cero: variables, punteros, gestión manual de memoria, structs y programación de sistemas. Ideal para entender cómo funciona realmente un ordenador.",
    categoryId: "c",
    category: "C",
    categoryColor: "bg-cyan-600",
    branch: "systems",
    level: "beginner",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["C", "Sistemas", "Punteros", "Memoria", "Guía"],
    curriculum: [{ slug: "c-lang" }],
  },
  {
    id: "ruta-cpp",
    slug: "ruta-cpp",
    title: "Ruta C++",
    description:
      "Domina C++ moderno: POO, STL, smart pointers, move semantics y programación de alto rendimiento. Construye sobre los fundamentos de C.",
    categoryId: "cpp",
    category: "C++",
    categoryColor: "bg-cyan-600",
    branch: "systems",
    dependsOn: "ruta-c",
    level: "intermediate",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["C++", "POO", "STL", "Rendimiento", "Guía"],
    curriculum: [{ slug: "c-lang" }, { slug: "cpp-lang" }],
  },
  {
    id: "ruta-backend-js",
    slug: "ruta-backend-js",
    title: "Ruta Backend JavaScript",
    description:
      "Crea APIs REST profesionales con Node.js y Express, conecta bases de datos PostgreSQL y desplega un backend completo con Supabase. El contrapunto moderno a la ruta Java.",
    categoryId: "nodejs",
    category: "Node.js",
    categoryColor: "bg-green-600",
    branch: "backend",
    level: "intermediate",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Backend",
      "Node.js",
      "Express",
      "PostgreSQL",
      "Supabase",
      "API",
      "Guía",
    ],
    curriculum: [
      { slug: "javascript" },
      { slug: "node-express" },
      { slug: "sql-basics" },
      { slug: "postgresql-guide" },
      { slug: "supabase-guide" },
    ],
  },
  {
    id: "ruta-databases",
    slug: "ruta-databases",
    title: "Ruta Bases de Datos",
    description:
      "Domina los datos: qué son las bases de datos, SQL relacional y NoSQL, y trabaja con MySQL, PostgreSQL, MongoDB y Supabase hasta elegir la tecnología adecuada para cada proyecto.",
    categoryId: "sql",
    category: "Bases de Datos",
    categoryColor: "bg-blue-600",
    branch: "backend",
    level: "beginner",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "SQL",
      "NoSQL",
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Supabase",
      "Guía",
    ],
    curriculum: [
      { slug: "database-intro" },
      { slug: "sql-vs-nosql" },
      { slug: "sql-basics" },
      { slug: "mysql-guide" },
      { slug: "postgresql-guide" },
      { slug: "mongodb-guide" },
      { slug: "supabase-guide" },
    ],
  },
  {
    id: "ruta-python-ia",
    slug: "ruta-python-ia",
    title: "Ruta Python & IA",
    description:
      "Aprende Python y conviértete en ingeniero de IA: crea proyectos asistidos, elige framework de agentes, lanza agentes en paralelo y construye asistentes con RAG.",
    categoryId: "python",
    category: "Python",
    categoryColor: "bg-sky-500",
    branch: "ai",
    level: "intermediate",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-07-01",
    featured: true,
    tags: ["Python", "IA", "Agentes", "RAG", "Frameworks", "OpenCode", "Guía"],
    curriculum: [
      { slug: "python" },
      { slug: "ai-project" },
      { slug: "frameworks-agentes" },
      { slug: "agentes-paralelo" },
      { slug: "rag-con-mcp" },
    ],
  },
  {
    id: "ruta-fullstack",
    slug: "ruta-fullstack",
    title: "Ruta Full-Stack",
    description:
      "Unifica frontend y backend en una sola app: React, Next.js, API con Node y Express, base de datos con Supabase y testing end-to-end. La ruta que une las ramas Web y Backend.",
    categoryId: "nextjs",
    category: "Full-Stack",
    categoryColor: "bg-black",
    branch: "web",
    joins: ["web", "backend"],
    dependsOn: "ruta-frontend",
    level: "advanced",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-07-01",
    featured: true,
    tags: [
      "Full-Stack",
      "Next.js",
      "React",
      "Express",
      "Supabase",
      "Testing",
      "Guía",
    ],
    curriculum: [
      { slug: "javascript" },
      { slug: "typescript" },
      { slug: "react-framework" },
      { slug: "nextjs-framework" },
      { slug: "node-express" },
      { slug: "supabase-guide" },
      { slug: "testing-frontend" },
    ],
  },
  {
    id: "ruta-angular",
    slug: "ruta-angular",
    title: "Ruta Angular",
    description:
      "Del TypeScript a aplicaciones Angular enterprise: componentes standalone, directivas, services, HttpClient y routing. El camino de Angular sobre los fundamentos de la ruta frontend.",
    categoryId: "angular",
    category: "Angular",
    categoryColor: "bg-red-600",
    branch: "web",
    dependsOn: "ruta-frontend",
    level: "intermediate",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["Angular", "Frontend", "TypeScript", "Componentes", "SPA", "Guía"],
    curriculum: [{ slug: "typescript" }, { slug: "angular" }],
  },
  {
    id: "ruta-vue",
    slug: "ruta-vue",
    title: "Ruta Vue",
    description:
      "JavaScript a Vue 3: Composition API, reactividad, directivas, props y emits, Vue Router y Pinia. El framework progresivo sobre la base de la ruta frontend.",
    categoryId: "vue",
    category: "Vue",
    categoryColor: "bg-emerald-500",
    branch: "web",
    dependsOn: "ruta-frontend",
    level: "intermediate",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["Vue", "Frontend", "JavaScript", "Composition API", "Vite", "Guía"],
    curriculum: [{ slug: "javascript" }, { slug: "vue" }],
  },
  {
    id: "ruta-css-diseno",
    slug: "ruta-css-diseno",
    title: "Ruta CSS & Diseño",
    description:
      "Convierte el CSS en una herramienta de diseño profesional: fundamentos, animaciones, layouts modernos con container queries y Tailwind CSS sobre la base de la ruta frontend.",
    categoryId: "css",
    category: "CSS",
    categoryColor: "bg-blue-400",
    branch: "web",
    dependsOn: "ruta-frontend",
    level: "intermediate",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-03",
    featured: true,
    tags: ["CSS", "Animaciones", "Tailwind", "Diseño", "Guía"],
    curriculum: [
      { slug: "html-css" },
      { slug: "css-avanzado" },
      { slug: "tailwind-css" },
    ],
  },
  {
    id: "ruta-javascript-moderno",
    slug: "ruta-javascript-moderno",
    title: "Ruta JavaScript Moderno",
    description:
      "Profundiza en JavaScript: fundamentos sólidos y después asincronía, fetch, módulos ES y las APIs del navegador modernas. El puente entre principiante y senior.",
    categoryId: "javascript",
    category: "JavaScript",
    categoryColor: "bg-yellow-500",
    branch: "web",
    dependsOn: "ruta-frontend",
    level: "intermediate",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-03",
    featured: true,
    tags: ["JavaScript", "Async", "Fetch", "DOM", "Módulos", "Guía"],
    curriculum: [{ slug: "javascript" }, { slug: "javascript-avanzado" }],
  },
  {
    id: "ruta-typescript-avanzado",
    slug: "ruta-typescript-avanzado",
    title: "Ruta TypeScript Avanzado",
    description:
      "Ve más allá de los tipos básicos: generics, utility types, narrowing, uniones discriminadas y tipado profesional de React con tsconfig estricto.",
    categoryId: "typescript",
    category: "TypeScript",
    categoryColor: "bg-blue-500",
    branch: "web",
    dependsOn: "ruta-frontend",
    level: "advanced",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-03",
    featured: true,
    tags: ["TypeScript", "Generics", "Tipado", "React", "Guía"],
    curriculum: [{ slug: "typescript" }, { slug: "typescript-avanzado" }],
  },
  {
    id: "ruta-apps-interactivas",
    slug: "ruta-apps-interactivas",
    title: "Ruta Apps Interactivas",
    description:
      "Convierte tus apps en productos: estado global con Zustand, data fetching con React Query, Next.js en producción, rendimiento con Core Web Vitals y accesibilidad WCAG.",
    categoryId: "react",
    category: "React",
    categoryColor: "bg-cyan-500",
    branch: "web",
    dependsOn: "ruta-frontend",
    level: "advanced",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-03",
    featured: true,
    tags: [
      "React",
      "Zustand",
      "Next.js",
      "Rendimiento",
      "Accesibilidad",
      "Guía",
    ],
    curriculum: [
      { slug: "react-framework" },
      { slug: "estado-global" },
      { slug: "nextjs-framework" },
      { slug: "rendimiento-frontend" },
      { slug: "accesibilidad" },
    ],
  },
  {
    id: "ruta-go",
    slug: "ruta-go",
    title: "Ruta Go",
    description:
      "Aprende Go desde cero: sintaxis, funciones, structs, interfaces, goroutines y un servidor HTTP. Un lenguaje moderno y rápido para backend de alto rendimiento.",
    categoryId: "go",
    category: "Go",
    categoryColor: "bg-cyan-500",
    branch: "backend",
    level: "beginner",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["Go", "Backend", "Goroutines", "HTTP", "Guía"],
    curriculum: [{ slug: "go" }],
  },
  {
    id: "ruta-rust",
    slug: "ruta-rust",
    title: "Ruta Rust",
    description:
      "Construye sobre los fundamentos de C para dominar Rust: ownership, structs, enums, traits y errores. Memoria segura y máximo rendimiento en sistemas.",
    categoryId: "rust",
    category: "Rust",
    categoryColor: "bg-orange-700",
    branch: "systems",
    dependsOn: "ruta-c",
    level: "intermediate",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["Rust", "Sistemas", "Ownership", "Cargo", "Guía"],
    curriculum: [{ slug: "c-lang" }, { slug: "rust" }],
  },
  {
    id: "ruta-nestjs",
    slug: "ruta-nestjs",
    title: "Ruta NestJS",
    description:
      "Estructura tu backend con NestJS: módulos, controllers, services, DTOs con validación, TypeORM, guards con JWT y Swagger. Sobre la base de TypeScript y Express.",
    categoryId: "nestjs",
    category: "NestJS",
    categoryColor: "bg-red-500",
    branch: "backend",
    dependsOn: "ruta-backend-js",
    level: "advanced",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["NestJS", "TypeScript", "Backend", "API", "Guía"],
    curriculum: [
      { slug: "typescript" },
      { slug: "node-express" },
      { slug: "nestjs" },
    ],
  },
  {
    id: "ruta-devops",
    slug: "ruta-devops",
    title: "Ruta DevOps",
    description:
      "Automatiza el ciclo de vida de tus aplicaciones: Git, Docker, CI/CD con GitHub Actions y Kubernetes. La ruta que une Web y Backend para llevar tu stack a producción.",
    categoryId: "ci-cd",
    category: "DevOps",
    categoryColor: "bg-violet-600",
    branch: "backend",
    joins: ["web", "backend"],
    dependsOn: "ruta-fullstack",
    level: "advanced",
    readTime: "—",
    estimatedMinutes: 0,
    publishedAt: "2026-08-01",
    featured: true,
    tags: ["DevOps", "Docker", "CI/CD", "Kubernetes", "Git", "Guía"],
    curriculum: [
      { slug: "git" },
      { slug: "docker" },
      { slug: "ci-cd" },
      { slug: "kubernetes" },
    ],
  },
];

export function getGuides(): GuideMeta[] {
  return [...allGuides];
}

export function getGuideBySlug(slug: string): GuideMeta | undefined {
  return allGuides.find((g) => g.slug === slug);
}

export function resolveCurriculumMeta(
  guide: GuideMeta,
): (ContentMeta & { optional?: boolean })[] {
  return guide.curriculum
    .map((step) => {
      const meta = allContent.find((c) => c.slug === step.slug);

      return meta ? { ...meta, optional: step.optional ?? false } : null;
    })
    .filter(Boolean) as (ContentMeta & { optional?: boolean })[];
}

export function guideTotalMinutes(guide: GuideMeta): number {
  const steps = resolveCurriculumMeta(guide);

  return steps.reduce((sum, s) => sum + (s.estimatedMinutes ?? 0), 0);
}

// ── Query helpers ─────────────────────────────────────────────────────────────

export function getContentByType(type: ContentType): ContentMeta[] {
  return [...allContent]
    .filter((c) => c.type === type)
    .sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
}

export function getContentBySlug(
  slug: string,
  type?: ContentType,
): ContentMeta | undefined {
  return allContent.find((c) => c.slug === slug && (!type || c.type === type));
}

export function getContentByCategory(categoryId: string): ContentMeta[] {
  return allContent.filter((c) => c.categoryId === categoryId);
}

export function getContentByLevel(level: DifficultyLevel): ContentMeta[] {
  return allContent.filter((c) => c.level === level);
}

export function getContentByLearningPath(
  pathId: LearningPathId,
): ContentMeta[] {
  return allContent.filter((c) => c.learningPaths?.includes(pathId));
}

export function getCategoriesByType(type: ContentType): string[] {
  return [...new Set(getContentByType(type).map((c) => c.categoryId))];
}

export function getTagsByType(type: ContentType): string[] {
  return [
    ...new Set(getContentByType(type).flatMap((c) => c.tags ?? [])),
  ].sort();
}

export function getSubcategoriesByType(type: ContentType): string[] {
  return [
    ...new Set(
      getContentByType(type)
        .map((c) => c.subcategory)
        .filter(Boolean),
    ),
  ] as string[];
}

export function getLatestContent(): ContentMeta {
  return allContent.reduce((latest, item) =>
    item.publishedAt > latest.publishedAt ? item : latest,
  );
}

export function getFeaturedContent(): ContentMeta[] {
  return allContent.filter((c) => c.featured);
}

export function getContentByTag(tag: string): ContentMeta[] {
  return allContent.filter((c) =>
    c.tags?.some((t) => t.toLowerCase() === tag.toLowerCase()),
  );
}

export function searchContent(
  query: string,
  type?: ContentType,
): ContentMeta[] {
  const q = query.toLowerCase().trim();

  if (!q) return type ? getContentByType(type) : [...allContent];

  return allContent.filter((c) => {
    if (type && c.type !== type) return false;

    return (
      c.title.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.category.toLowerCase().includes(q) ||
      c.categoryId.toLowerCase().includes(q) ||
      c.tags?.some((t) => t.toLowerCase().includes(q))
    );
  });
}

export function filterContent(opts: {
  type?: ContentType;
  categoryId?: string;
  level?: DifficultyLevel;
  tag?: string;
  learningPath?: LearningPathId;
  query?: string;
}): ContentMeta[] {
  return allContent.filter((c) => {
    if (opts.type && c.type !== opts.type) return false;
    if (opts.categoryId && c.categoryId !== opts.categoryId) return false;
    if (opts.level && c.level !== opts.level) return false;
    if (
      opts.tag &&
      !c.tags?.some((t) => t.toLowerCase() === opts.tag!.toLowerCase())
    )
      return false;
    if (opts.learningPath && !c.learningPaths?.includes(opts.learningPath))
      return false;
    if (opts.query) {
      const q = opts.query.toLowerCase();
      const match =
        c.title.toLowerCase().includes(q) ||
        c.description.toLowerCase().includes(q) ||
        c.categoryId.includes(q) ||
        c.tags?.some((t) => t.toLowerCase().includes(q));

      if (!match) return false;
    }

    return true;
  });
}

export function formatDate(iso: string): string {
  return new Date(iso + "T00:00:00").toLocaleDateString("es-ES", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export function typeLabel(type: ContentType): string {
  const map: Record<ContentType, string> = {
    article: "blog.type.article",
    tutorial: "blog.type.tutorial",
    tool: "blog.type.tool",
  };

  return map[type];
}

export function typeLabelPlural(type: ContentType): string {
  const map: Record<ContentType, string> = {
    article: "blog.type.articles",
    tutorial: "blog.type.tutorials",
    tool: "blog.type.tools",
  };

  return map[type];
}

export function typeSlug(type: ContentType): string {
  return { article: "articulos", tutorial: "tutoriales", tool: "herramientas" }[
    type
  ];
}

export function contentHref(type: ContentType, slug: string): string {
  const base: Record<ContentType, string> = {
    article: "/blog",
    tutorial: "/campus",
    tool: "/blog",
  };

  return `${base[type]}/${typeSlug(type)}/${slug}`;
}
